"use strict";

const dapi = require("../../../utils/dapi");
const { monthRemainingDays } = require("../../../utils/date");

function getDaysContents(data) {
  const everyDay = ["video", "activity"];
  const every3Day = ["game", "audio", "book"];
  const result = [];
  const remainingDays = monthRemainingDays(new Date());

  for (let i = 0; i < remainingDays; i++) {
    const todayContents = [];
    everyDay.forEach((type) => {
      const contents = data[type].slice(2 * i, 2 * (i + 1)).map((id) => {
        type, id;
      });
      todayContents.push(...contents);
    });

    let j = i;
    while (j < i + 3) {
      todayTypeSelected = every3Day[j % 3];
      const contents = data[type]
        .slice(Math.floor((2 / 3) * i), 2 * Math.floor(i / 3 + 1))
        .map((id) => {
          type, id;
        });
      if (contents.length !== 2) {
        j += 1;
        continue;
      }
      todayContents.push(...contents);
      break;
    }

    result.push(todayContents);
  }

  return result;
}

module.exports = ({ strapi }) => ({
  async fetch(child) {
    const { gender } = child;
    const age = strapi.service("api::child.extended").age(child);
    const days = monthRemainingDays(new Date());

    const growthField = await strapi
      .service("api::child-step.extended")
      .growthField(child.id);
    const field = growthField.symbol;

    return await dapi.plan({ age, gender, days, field });
  },

  async generate(child) {
    const plan = await this.fetch(child);
    const activityService = strapi.service("api::activity.activity");

    const daysContents = getDaysContents(plan.data);

    await daysContents.reduce(async (acc, contents, day) => {
      await acc;
      return createActivities(contents, day);
    }, Promise.resolve());

    await strapi.service("api::child-step.extended").generated(childStep);

    async function createActivities(contents, day) {
      await contents.reduce(async (acc, content) => {
        await acc;
        return createActivity(content, day);
      });
    }

    async function createActivity(content, day) {
      await activityService.create({
        data: {
          child,
          type: content.type,
          content: content.id,
          date: format(addDays(now, day), "yyyy-MM-dd"),
          autoGenerated: true,
        },
      });
    }
  },
});
